export const GET_TASK_LIST = "GET_TASK_LIST";
export const DND_IN_SAME_SECTION = "DND_IN_SAME_SECTION";
export const DND_IN_DIFFERENT_SECTION = "DND_IN_DIFFERENT_SECTION";
export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const CLEAR_REDUCER = "CLEAR_REDUCER";